# Generated by Django 4.2.4 on 2023-08-30 16:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_alter_problem_theme"),
    ]

    operations = [
        migrations.AlterField(
            model_name="problem",
            name="difficulty",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Сложность"
            ),
        ),
    ]
